# Generated by Django 5.0.4 on 2024-04-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_subject_quiz_file_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerreason',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subject',
            name='quiz_file',
            field=models.FileField(default='none', upload_to='quiz/'),
        ),
    ]
