# Generated by Django 5.0.4 on 2024-05-15 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_answerreason_image_alter_subject_quiz_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizes.question')),
            ],
        ),
    ]
